project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "index.qmd"
    - "about.qmd"
    - "experience.qmd"              
    - "projects.qmd"
    - "career.qmd"
  resources:
    - "content/"
    - "css"
    - "splitkbcompare.html"
    - "static/"

website:
  title: "Tarun Kumanduri"
  description: "Personal Website"
  image: images/profile/tarun.png
  site-url: https://www.tarunkumanduri.netlify.app
  favicon: images/favicon/favicon.ico
  repo-url: https://github.com/TarunKumanduri1
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: false

  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Experience"
        href: experience.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Career Highlights"
        href: career.qmd

  page-footer:
    center:
      - text: |
          Contact: <a href="mailto:tarun.kumanduri99@gmail.com">tarun.kumanduri99@gmail.com</a><br>
          <a href="https://www.linkedin.com/company/tarun-kumanduri" target="_blank"><i class="bi bi-linkedin"></i> LinkedIn </a> &nbsp; | &nbsp;
          <a href="https://github.com/TarunKumanduri1" target="_blank"><i class="bi bi-github"></i> GitHub</a>

format:
  html:
    theme: [default, css/theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: "_includes/header.html"
